// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'dart:io' show Platform;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Platform.environment['WEB_API_KEY'] ?? '',
    appId: '1:546282503490:web:f8ab3f3acc56b8ece19cdb',
    messagingSenderId: '546282503490',
    projectId: 'baby-binder',
    authDomain: 'baby-binder.firebaseapp.com',
    storageBucket: 'baby-binder.appspot.com',
    measurementId: 'G-DEE58HF0MR',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Platform.environment['ANDROID_API_KEY'] ?? '',
    appId: '1:546282503490:android:869198139f3e4c21e19cdb',
    messagingSenderId: '546282503490',
    projectId: 'baby-binder',
    storageBucket: 'baby-binder.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Platform.environment['IOS_API_KEY'] ?? '',
    appId: '1:546282503490:ios:13704d548e61946ee19cdb',
    messagingSenderId: '546282503490',
    projectId: 'baby-binder',
    storageBucket: 'baby-binder.appspot.com',
    iosClientId:
        '546282503490-gq8d5t56lfa7rvsfj9hoaun8lv910uuv.apps.googleusercontent.com',
    iosBundleId: 'com.mattmanhardt.babybinder',
  );
}
